---
create_user: your_admin_user
new_hostname: your_hostname
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'net-tools', 'dos2unix', 'unzip' ]
